(function(){
"use strict";
var KEY="amazon_compuesto_operations_v1";
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x:[]}catch(e){return []}}
function save(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch(e){}}
function esc(x){return String(x==null?"":x).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function money(x){return x==null||!isFinite(x)?"—":"$"+Number(x).toFixed(2)}
function num(x){var n=Number(x);return isFinite(n)?n:null}
function delta(actual,pred){return actual==null||pred==null?null:actual-pred}
function pct(x){return x==null||!isFinite(x)?"—":(Number(x)*100).toFixed(1)+"%"}
function snapshot(kind){
 var e=window.MOTOR_SCORING_ENGINE;if(!e)return null;
 var s={};try{s=JSON.parse(localStorage.getItem("jev_v1")||"{}")}catch(_){}
 var p=s.product||{},f=e.financial||{},c=e.capital||{},d=e.final||{},r=window.MOTOR_SCORING_PHASE5&&window.MOTOR_SCORING_PHASE5.rotation,k=window.MOTOR_SCORING_PHASE5&&window.MOTOR_SCORING_PHASE5.risk,mk=window.MOTOR_SCORING_MARKET&&window.MOTOR_SCORING_MARKET.result;
 kind=kind==="COMPRA"?"COMPRA":"ANALISIS";
 return {id:"OP-"+Date.now(),createdAt:new Date().toISOString(),kind:kind,status:kind==="COMPRA"?"PENDIENTE_COMPRA":"ANALISIS",product:{asin:p.asin||"",upcEan:p.upcEan||"",brand:p.brand||"",marketplace:p.marketplace||""},prediction:{units:d.pilotUnits||c.pilotUnits||null,investment:d.pilotCapital||c.pilotCapital||null,roi:f.roi,margin:f.margin,price:Number(document.getElementById("p_precio")&&document.getElementById("p_precio").value)||null,daysToCash:r&&r.dtc!=null?r.dtc:null,financialScore:f.score,rotationScore:r&&r.score!=null?r.score:null,marketScore:mk&&mk.score!=null?mk.score:null,riskScore:k&&k.score!=null?k.score:null,capitalEfficiency:c.score,dataConfidence:e.confidence&&e.confidence.score,decision:d.decision,score:d.score},purchase:null,actual:{unitsSold:null,price:null,roi:null,margin:null,returns:null,daysToCash:null,profit:null}};
}
function styles(){if(document.getElementById("ops-style"))return;var x=document.createElement("style");x.id="ops-style";x.textContent=".ops-box{margin:14px 0;padding:14px;border:1px solid var(--line);background:#fff}.ops-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.ops-actions{display:flex;gap:8px;flex-wrap:wrap}.ops-btn{padding:9px 12px;border:1px solid var(--deep);background:#fff;cursor:pointer;font-weight:700}.ops-btn:disabled{opacity:.45;cursor:not-allowed}.ops-row{border-top:1px solid var(--line);padding:10px 0;font-size:12px;line-height:1.5}.ops-muted{color:var(--muted);font-size:11px}.ops-empty{color:var(--muted);padding-top:8px}.ops-close{margin-top:10px;padding:12px;border:1px solid var(--line);background:#fafafa}.ops-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:10px 0}.ops-grid label{font-size:11px;color:var(--muted)}.ops-grid input{width:100%;box-sizing:border-box;padding:8px;margin-top:4px;border:1px solid var(--line);background:#fff;color:var(--ink)}@media(max-width:620px){.ops-head{align-items:flex-start;flex-direction:column}.ops-grid{grid-template-columns:1fr}}";document.head.appendChild(x)}
function purchaseForm(o){var q=o.prediction||{},host=document.getElementById("ops-editor");if(!host)return;host.innerHTML='<div class="ops-close"><b>Registrar compra '+esc(o.id)+'</b><div class="ops-muted">La recomendación JEV queda congelada como predicción. Aquí registra lo que realmente compraste.</div><div class="ops-grid"><label>Unidades compradas<input id="op-buy-units" type="number" min="1" step="1" value="'+esc(q.units==null?"":q.units)+'"></label><label>Inversión real US$<input id="op-buy-investment" type="number" min="0" step="0.01" value="'+esc(q.investment==null?"":Number(q.investment).toFixed(2))+'"></label></div><button id="op-buy-confirm" class="ops-btn">Confirmar compra</button> <button id="op-buy-cancel" class="ops-btn">Cancelar</button></div>';
 document.getElementById("op-buy-cancel").onclick=function(){host.innerHTML=""};
 document.getElementById("op-buy-confirm").onclick=function(){var units=num(document.getElementById("op-buy-units").value),investment=num(document.getElementById("op-buy-investment").value);if(units==null||units<1||investment==null||investment<0){alert("Completa unidades e inversión real de la compra.");return}o.purchase={units:Math.round(units),investment:investment,registeredAt:new Date().toISOString()};o.status="ABIERTA";var ops=load();ops.push(o);save(ops);render()};
}
function closeForm(id){var ops=load(),o=ops.filter(function(x){return x.id===id})[0];if(!o)return;var q=o.prediction||{},a=o.actual||{};var html='<div class="ops-close"><b>Cerrar '+esc(id)+'</b><div class="ops-grid">' +
'<label>Unidades vendidas<input id="op-units" type="number" min="0" value="'+esc(a.unitsSold==null?"":a.unitsSold)+'"></label>' +
'<label>Precio real/u<input id="op-price" type="number" step="0.01" value="'+esc(a.price==null?"":a.price)+'"></label>' +
'<label>ROI real %<input id="op-roi" type="number" step="0.1" value="'+esc(a.roi==null?"":(a.roi*100).toFixed(1))+'"></label>' +
'<label>Margen real %<input id="op-margin" type="number" step="0.1" value="'+esc(a.margin==null?"":(a.margin*100).toFixed(1))+'"></label>' +
'<label>Devoluciones<input id="op-returns" type="number" min="0" value="'+esc(a.returns==null?"":a.returns)+'"></label>' +
'<label>Days to Cash real<input id="op-dtc" type="number" min="0" value="'+esc(a.daysToCash==null?"":a.daysToCash)+'"></label>' +
'<label>Beneficio/pérdida total US$<input id="op-profit" type="number" step="0.01" value="'+esc(a.profit==null?"":a.profit)+'"></label></div><button id="op-confirm" class="ops-btn">Cerrar operación</button> <button id="op-cancel" class="ops-btn">Cancelar</button></div>';var host=document.getElementById("ops-editor");host.innerHTML=html;document.getElementById("op-cancel").onclick=function(){host.innerHTML=""};document.getElementById("op-confirm").onclick=function(){var units=num(document.getElementById("op-units").value),price=num(document.getElementById("op-price").value),roi=num(document.getElementById("op-roi").value),margin=num(document.getElementById("op-margin").value),returns=num(document.getElementById("op-returns").value),dtc=num(document.getElementById("op-dtc").value),profit=num(document.getElementById("op-profit").value);if(units==null||price==null||roi==null||margin==null||returns==null||dtc==null||profit==null){alert("Completa todos los resultados reales antes de cerrar.");return}o.actual={unitsSold:units,price:price,roi:roi/100,margin:margin/100,returns:returns,daysToCash:dtc,profit:profit};o.status="CERRADA";o.closedAt=new Date().toISOString();o.variance={price:delta(o.actual.price,q.price),roi:delta(o.actual.roi,q.roi),margin:delta(o.actual.margin,q.margin),daysToCash:delta(o.actual.daysToCash,q.daysToCash)};save(ops);render()}}
function render(){
 var root=document.getElementById("operations_history");if(!root)return;var ops=load(),engine=window.MOTOR_SCORING_ENGINE,canBuy=!!(engine&&engine.final&&engine.final.decision==="COMPRAR PILOTO");
 root.innerHTML='<div class="ops-head"><div><div class="cardtitle">Registro de análisis y operaciones · v1</div><div class="ops-muted">ANÁLISIS guarda lo que JEV pensó. COMPRA abre seguimiento real y permite comparar predicción vs resultado.</div></div><div class="ops-actions"><button id="ops-analysis" class="ops-btn">Guardar análisis</button><button id="ops-buy" class="ops-btn" '+(canBuy?'':'disabled')+'>Registrar compra</button></div></div><div id="ops-list">'+(ops.length?ops.slice().reverse().map(function(o){var q=o.prediction||{},a=o.actual||{},v=o.variance||{},kind=o.kind||(o.status==="ANALISIS"?"ANALISIS":"COMPRA"),buy=o.purchase||null;return '<div class="ops-row"><b>'+esc(o.id)+'</b> · '+esc(kind)+' · '+esc(o.status)+' · '+esc(o.product.asin||"SIN ASIN")+'<br><b>PREDICCIÓN:</b> '+esc(q.decision||"—")+' · '+(q.units==null?'u —':'u '+q.units)+' · inversión '+money(q.investment)+' · ROI '+pct(q.roi)+' · margen '+pct(q.margin)+' · DTC '+(q.daysToCash==null?"—":Math.round(q.daysToCash)+" días")+(buy?'<br><b>COMPRA REAL:</b> '+buy.units+' u · inversión '+money(buy.investment):'')+(o.status==="CERRADA"?'<br><b>RESULTADO REAL:</b> beneficio '+money(a.profit)+' · ROI '+pct(a.roi)+' · margen '+pct(a.margin)+' · DTC '+Math.round(a.daysToCash)+' días · devoluciones '+a.returns+'<br><span class="ops-muted">DESVIACIÓN: precio '+money(v.price)+' · ROI '+pct(v.roi)+' · margen '+pct(v.margin)+' · DTC '+(v.daysToCash==null?"—":(v.daysToCash>0?"+":"")+Math.round(v.daysToCash)+" días")+'</span>':(o.status==="ABIERTA"?'<br><button class="ops-btn ops-close-btn" data-id="'+esc(o.id)+'">Registrar resultado real</button>':''))+'<br><span class="ops-muted">Financial '+(q.financialScore==null?"—":q.financialScore)+' · Rotation '+(q.rotationScore==null?"—":q.rotationScore)+' · Market '+(q.marketScore==null?"—":q.marketScore)+' · Risk '+(q.riskScore==null?"—":q.riskScore)+' · Confidence '+(q.dataConfidence==null?"—":q.dataConfidence)+'</span></div>'}).join(""):'<div class="ops-empty">Todavía no hay análisis ni operaciones registradas.</div>')+'</div><div id="ops-editor"></div>';
 Array.prototype.forEach.call(document.querySelectorAll(".ops-close-btn"),function(x){x.onclick=function(){closeForm(this.getAttribute("data-id"))}});
 var a=document.getElementById("ops-analysis");if(a)a.onclick=function(){var o=snapshot("ANALISIS");if(!o){alert("El Motor Scoring todavía no está listo.");return}var list=load();list.push(o);save(list);render()};
 var b=document.getElementById("ops-buy");if(b)b.onclick=function(){var o=snapshot("COMPRA");if(!o||o.prediction.decision!=="COMPRAR PILOTO"){alert("JEV no recomienda compra con la decisión actual.");return}purchaseForm(o)};
}
function init(attempt){attempt=attempt||0;var anchor=document.getElementById("jev_final_decision");if(!anchor){if(attempt<80)setTimeout(function(){init(attempt+1)},100);return}if(document.getElementById("operations_history"))return;styles();var d=document.createElement("div");d.id="operations_history";d.className="ops-box";anchor.parentNode.insertBefore(d,anchor.nextSibling);render();if(window.MutationObserver)new MutationObserver(function(){render()}).observe(anchor,{childList:true,subtree:true,characterData:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(function(){init(0)},50)});else setTimeout(function(){init(0)},50);
window.AMAZON_COMPOUND_OPERATIONS={load:load,render:render,snapshot:snapshot,mount:function(){init(0)}};
})();