(function(){
"use strict";
var KEY="amazon_compuesto_operations_v1";
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x:[]}catch(e){return []}}
function save(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch(e){}}
function esc(x){return String(x==null?"":x).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function money(x){return x==null||!isFinite(x)?"—":"$"+Number(x).toFixed(2)}
function pct(x){return x==null||!isFinite(x)?"—":(Number(x)*100).toFixed(1)+"%"}
function num(x){var n=Number(x);return isFinite(n)?n:null}
function readState(){try{var s=JSON.parse(localStorage.getItem("jev_v1")||"{}");return s&&typeof s==="object"?s:{}}catch(e){return {}}}
function domNumber(id){var e=document.getElementById(id);if(!e||e.value==="")return null;var n=Number(e.value);return isFinite(n)?n:null}
function domValue(id){var e=document.getElementById(id);return e?e.value:""}

function captureCostModel(){
 var s=readState(),costs=s.costs||{},c=costs.checkout||{},p=costs.prep||{},currency=domValue("p_moneda")||"USD",rate=currency==="USD"?1:domNumber("p_tc");
 return {currency:currency,rate:rate,displayedUnit:c.displayedUnit==null?null:Number(c.displayedUnit),discountUnit:c.discountUnit==null?0:Number(c.discountUnit),taxUnit:c.taxUnit==null?null:Number(c.taxUnit),supplierToPrepLot:c.supplierToPrepLot==null?null:Number(c.supplierToPrepLot),prepUnit:p.prepUnit==null?null:Number(p.prepUnit),otherPrepLot:p.otherPrepLot==null?0:Number(p.otherPrepLot),prepToAmazonLot:p.prepToAmazonLot==null?null:Number(p.prepToAmazonLot)};
}
function costBreakdown(m,units){
 units=Number(units);if(!m||!isFinite(units)||units<1)return null;var rate=Number(m.rate);if(!isFinite(rate)||rate<=0)return null;
 var displayed=Number(m.displayedUnit),discount=Number(m.discountUnit||0),tax=Number(m.taxUnit),supplier=Number(m.supplierToPrepLot),prep=Number(m.prepUnit),other=Number(m.otherPrepLot||0),prepAmazon=Number(m.prepToAmazonLot);
 if([displayed,discount,tax,supplier,prep,other,prepAmazon].some(function(v){return !isFinite(v)}))return null;
 var productUnitUSD=Math.max(0,displayed-discount+tax)/rate,supplierUSD=supplier/rate,productTotal=productUnitUSD*units,prepTotal=prep*units,total=productTotal+prepTotal+supplierUSD+other+prepAmazon;
 return {units:units,productUnitUSD:productUnitUSD,productTotal:productTotal,prepUnit:prep,prepUnitTotal:prepTotal,supplierToPrepLotUSD:supplierUSD,otherPrepLot:other,prepToAmazonLot:prepAmazon,total:total};
}
function projectedInvestment(q,units){var b=costBreakdown(q&&q.costModel,units);if(b)return b.total;var ru=Number(q&&q.units),ri=Number(q&&q.investment);return ru>0&&isFinite(ri)?ri/ru*units:ri}
function breakdownHtml(q,units){var b=costBreakdown(q&&q.costModel,units);if(!b)return '<div class="ops-muted">No hay desglose disponible.</div>';return '<div class="ops-costs"><div class="ops-muted"><b>Desglose de capital antes de vender</b></div><div class="ops-costs-row"><span>Producto / checkout</span><span>'+units+' × '+money(b.productUnitUSD)+' = '+money(b.productTotal)+'</span></div><div class="ops-costs-row"><span>Prep Center por unidad</span><span>'+units+' × '+money(b.prepUnit)+' = '+money(b.prepUnitTotal)+'</span></div><div class="ops-costs-row"><span>Flete proveedor → Prep · lote</span><span>'+money(b.supplierToPrepLotUSD)+'</span></div><div class="ops-costs-row"><span>Otros costos Prep · lote</span><span>'+money(b.otherPrepLot)+'</span></div><div class="ops-costs-row"><span>Flete Prep → Amazon · lote</span><span>'+money(b.prepToAmazonLot)+'</span></div><div class="ops-costs-row ops-costs-total"><span>Capital total comprometido</span><span>'+money(b.total)+'</span></div></div>'}

function snapshot(kind){
 var e=window.MOTOR_SCORING_ENGINE;if(!e)return null;var s=readState(),p=s.product||{},f=e.financial||{},c=e.capital||{},d=e.final||{},r=window.MOTOR_SCORING_PHASE5&&window.MOTOR_SCORING_PHASE5.rotation,k=window.MOTOR_SCORING_PHASE5&&window.MOTOR_SCORING_PHASE5.risk,m=window.MOTOR_SCORING_MARKET&&window.MOTOR_SCORING_MARKET.result;
 return {id:"OP-"+Date.now(),createdAt:new Date().toISOString(),kind:kind,status:kind==="COMPRA"?"PENDIENTE_COMPRA":"ANALISIS",product:{asin:p.asin||"",brand:p.brand||"",marketplace:p.marketplace||""},prediction:{units:d.pilotUnits||c.pilotUnits||null,investment:d.pilotCapital||c.pilotCapital||null,roi:f.roi,margin:f.margin,price:domNumber("p_precio"),daysToCash:r&&r.dtc!=null?r.dtc:null,financialScore:f.score,rotationScore:r&&r.score!=null?r.score:null,marketScore:m&&m.score!=null?m.score:null,riskScore:k&&k.score!=null?k.score:null,capitalEfficiency:c.score,dataConfidence:e.confidence&&e.confidence.score,decision:d.decision,score:d.score,costModel:captureCostModel()},purchase:null,actual:{}};
}
function styles(){if(document.getElementById("ops-style"))return;var x=document.createElement("style");x.id="ops-style";x.textContent=".ops-box{margin:14px 0;padding:14px;border:1px solid var(--line);background:#fff}.ops-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.ops-actions{display:flex;gap:8px;flex-wrap:wrap}.ops-btn{padding:9px 12px;border:1px solid var(--deep);background:#fff;cursor:pointer;font-weight:700}.ops-btn:disabled{opacity:.45;cursor:not-allowed}.ops-muted{color:var(--muted);font-size:11px}.ops-editor{margin-top:10px}.ops-close{padding:12px;border:1px solid var(--lineStrong);background:#fafafa}.ops-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:10px 0}.ops-grid label{font-size:11px;color:var(--muted)}.ops-grid input{width:100%;padding:8px;margin-top:4px;border:1px solid var(--line)}.ops-costs{margin:10px 0;padding:10px;border:1px solid var(--line);background:#fff;font-size:11px}.ops-costs-row{display:flex;justify-content:space-between;gap:12px}.ops-costs-total{margin-top:6px;padding-top:6px;border-top:1px solid var(--line);font-weight:700}.ops-row{border-top:1px solid var(--line);padding:10px 0;font-size:12px;line-height:1.5}.ops-empty{color:var(--muted);padding-top:10px}@media(max-width:620px){.ops-head{align-items:flex-start;flex-direction:column}.ops-grid{grid-template-columns:1fr}}";document.head.appendChild(x)}

function purchaseForm(o){
 var q=o.prediction||{},host=document.getElementById("ops-editor");if(!host)return;var units=q.units||1,initial=projectedInvestment(q,units);
 host.innerHTML='<div class="ops-close"><b>Registrar compra '+esc(o.id)+'</b><div class="ops-muted">La recomendación del Motor Scoring queda congelada como predicción.</div><div class="ops-grid"><label>Unidades compradas<input id="op-buy-units" type="number" min="1" step="1" value="'+esc(units)+'"></label><label>Inversión real US$<input id="op-buy-investment" type="number" min="0" step="0.01" value="'+esc(Number(initial||0).toFixed(2))+'"></label></div><div id="op-buy-breakdown"></div><button id="op-buy-confirm" class="ops-btn">Confirmar compra</button> <button id="op-buy-cancel" class="ops-btn">Cancelar</button></div>';
 function refresh(){var u=num(document.getElementById("op-buy-units").value),inv=document.getElementById("op-buy-investment"),bd=document.getElementById("op-buy-breakdown");if(u!=null&&u>=1){var p=projectedInvestment(q,u);if(inv&&p!=null&&isFinite(p))inv.value=Number(p).toFixed(2);if(bd)bd.innerHTML=breakdownHtml(q,u)}}
 document.getElementById("op-buy-units").addEventListener("input",refresh);refresh();
 document.getElementById("op-buy-cancel").onclick=function(){host.innerHTML=""};
 document.getElementById("op-buy-confirm").onclick=function(){var u=num(document.getElementById("op-buy-units").value),inv=num(document.getElementById("op-buy-investment").value);if(u==null||u<1||inv==null||inv<0){alert("Completa unidades e inversión real.");return}u=Math.round(u);o.purchase={units:u,investment:inv,costBreakdown:costBreakdown(q.costModel,u),registeredAt:new Date().toISOString()};o.status="ABIERTA";var ops=load();ops.push(o);save(ops);render()};
 try{host.scrollIntoView({behavior:"smooth",block:"nearest"})}catch(e){}
}

function closeForm(id){var ops=load(),o=ops.filter(function(x){return x.id===id})[0];if(!o)return;var host=document.getElementById("ops-editor");host.innerHTML='<div class="ops-close"><b>Registrar resultado real '+esc(id)+'</b><div class="ops-grid"><label>Unidades vendidas<input id="op-units" type="number" min="0"></label><label>Precio real/u<input id="op-price" type="number" step="0.01"></label><label>ROI real %<input id="op-roi" type="number" step="0.1"></label><label>Margen real %<input id="op-margin" type="number" step="0.1"></label><label>Devoluciones<input id="op-returns" type="number" min="0"></label><label>Days to Cash real<input id="op-dtc" type="number" min="0"></label><label>Beneficio/pérdida total US$<input id="op-profit" type="number" step="0.01"></label></div><button id="op-close-confirm" class="ops-btn">Cerrar operación</button> <button id="op-close-cancel" class="ops-btn">Cancelar</button></div>';document.getElementById("op-close-cancel").onclick=function(){host.innerHTML=""};document.getElementById("op-close-confirm").onclick=function(){var u=num(document.getElementById("op-units").value),pr=num(document.getElementById("op-price").value),roi=num(document.getElementById("op-roi").value),mar=num(document.getElementById("op-margin").value),ret=num(document.getElementById("op-returns").value),dtc=num(document.getElementById("op-dtc").value),profit=num(document.getElementById("op-profit").value);if([u,pr,roi,mar,ret,dtc,profit].some(function(v){return v==null})){alert("Completa todos los resultados reales.");return}o.actual={unitsSold:u,price:pr,roi:roi/100,margin:mar/100,returns:ret,daysToCash:dtc,profit:profit};o.status="CERRADA";o.closedAt=new Date().toISOString();save(ops);render()}}

function syncBuyButton(){var b=document.getElementById("ops-buy"),e=window.MOTOR_SCORING_ENGINE,can=!!(e&&e.final&&e.final.decision==="COMPRAR PILOTO");if(b)b.disabled=!can}
function render(){
 var root=document.getElementById("operations_history");if(!root)return;var ops=load(),e=window.MOTOR_SCORING_ENGINE,can=!!(e&&e.final&&e.final.decision==="COMPRAR PILOTO");
 root.innerHTML='<div class="ops-head"><div><div class="cardtitle">Registro de análisis y operaciones · v1</div><div class="ops-muted">ANÁLISIS guarda la predicción. COMPRA abre seguimiento real.</div></div><div class="ops-actions"><button id="ops-analysis" class="ops-btn">Guardar análisis</button><button id="ops-buy" class="ops-btn" '+(can?'':'disabled')+'>Registrar compra</button></div></div><div id="ops-editor" class="ops-editor"></div><div id="ops-list">'+(ops.length?ops.slice().reverse().map(function(o){var q=o.prediction||{},a=o.actual||{};return '<div class="ops-row"><b>'+esc(o.id)+'</b> · '+esc(o.kind)+' · '+esc(o.status)+' · '+esc(o.product.asin||"SIN ASIN")+'<br><b>PREDICCIÓN:</b> '+esc(q.decision||"—")+' · '+(q.units==null?'u —':'u '+q.units)+' · inversión '+money(q.investment)+' · ROI '+pct(q.roi)+' · margen '+pct(q.margin)+(o.purchase?'<br><b>COMPRA REAL:</b> '+o.purchase.units+' u · inversión '+money(o.purchase.investment):'')+(o.status==="CERRADA"?'<br><b>RESULTADO REAL:</b> beneficio '+money(a.profit)+' · ROI '+pct(a.roi)+' · margen '+pct(a.margin):'')+(o.status==="ABIERTA"?'<div class="ops-actions"><button class="ops-btn ops-close-btn" data-id="'+esc(o.id)+'">Registrar resultado real</button></div>':'')+'</div>'}).join(""):'<div class="ops-empty">Todavía no hay análisis ni operaciones registradas.</div>')+'</div>';
 var a=document.getElementById("ops-analysis");if(a)a.onclick=function(){var o=snapshot("ANALISIS");if(!o){alert("El Motor Scoring todavía no está listo.");return}var x=load();x.push(o);save(x);render()};
 var b=document.getElementById("ops-buy");if(b)b.onclick=function(){var o=snapshot("COMPRA");if(!o||o.prediction.decision!=="COMPRAR PILOTO"){alert("Motor Scoring no recomienda compra con la decisión actual.");return}purchaseForm(o)};
 Array.prototype.forEach.call(document.querySelectorAll(".ops-close-btn"),function(x){x.onclick=function(){closeForm(this.getAttribute("data-id"))}});
}
function init(attempt){attempt=attempt||0;var anchor=document.getElementById("jev_final_decision");if(!anchor){if(attempt<80)setTimeout(function(){init(attempt+1)},100);return}if(document.getElementById("operations_history"))return;styles();var d=document.createElement("div");d.id="operations_history";d.className="ops-box";anchor.parentNode.insertBefore(d,anchor.nextSibling);render();if(window.MutationObserver)new MutationObserver(function(){syncBuyButton()}).observe(anchor,{childList:true,subtree:true,characterData:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(function(){init(0)},50)});else setTimeout(function(){init(0)},50);
window.AMAZON_COMPOUND_OPERATIONS={load:load,render:render,snapshot:snapshot,mount:function(){init(0)}};
})();